### ISSUE TITLE
How to use without pip?

### ISSUE THREAD

**Issue by swaldhoer** [whitequark/sphinxcontrib-platformpicker#1]
First, thanks for this useful extension, this feature long time missing in Sphinx!

I like to include some dependencies in my repositories without having to depend on pypi, e.g. for sphinx_rtd_theme this is described in the [docs](https://sphinx-rtd-theme.readthedocs.io/en/stable/installing.html#via-git-or-download).

How to do it for that extension?

**Comment by whitequark** [comment]
I have no idea, sorry.

**Comment by swaldhoer** [comment]
Thanks for your fast answer! However I figured it out:

1. Copy ``sphinxcontrib-platformpicker/sphinxcontrib`` to ``_ext/sphinxcontrib``
1. Add the following to ``conf.py``:
   1. Add ``"./_ext/sphinxcontrib"`` to ``sys.path``
   1. Extend ``extensions`` with``"platformpicker"``

I think it would be nice to add this to documentation.

Edit: I would prepare a pull request if you agree.

**Comment by swaldhoer** [comment]
Sorry to annoy you, but the way described in bcb43dff7392a30224b374d0fed7ba98b7737750 does not work.

```
Could not import extension sphinxcontrib.platformpicker (exception: No module named 'sphinxcontrib.platformpicker')
```

Doing as you suggested is the normal way, however it does not work with this package (that's why I came up with this issue). Doing it the way I posted above works.

**Comment by whitequark** [comment]
Okay, then we need to figure out why the normal way doesn't work. But I don't have time for that.

**Comment by swaldhoer** [comment]
As RTD also stopped support for vendoring the theme, I think we can close this.
